### ISSUE TITLE
torやプロキシの規制機能

### ISSUE THREAD

**Issue by kgtkr** [kgtkr/anontown-server#12]

**Comment by WhiteCat6142** [comment]
そのようなファイヤーウォール的なセキュリティはpeerblock等の専用ソフトでやる方が一般的ですよ
プロキシ規制はヘッダーである程度弾く以上の事は難しいと思います

**Comment by kgtkr** [comment]
そうなんですね
セキュリティというより違法な書き込みの対策ですが、VPN Gateは規制が難しいみたいですね
Gate+Torだと規制不可能ですし・・・

**Comment by new2ch** [comment]
https://check.torproject.org/exit-addresses

**Comment by kgtkr** [comment]
出口ノード一覧か
サンクス

**Comment by kgtkr** [comment]
anontown-serverプロジェクト以外でやるので見送り
